# Generated by Django 3.1.14 on 2022-01-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0002_auto_20211128_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shp',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
